"""Capability → Enki micro-service route catalog, extracted from the Android APK.

Generated by scripts/extract_api_routes.py. A best-effort name match: the
referentiel capability maps to routes whose last path segment is the same
kebab-case name. Some capabilities have no direct route (derived server-side)
or use a differently-named endpoint, so absence here is a hint, not proof.

Regenerate with:
    python scripts/extract_api_routes.py <apk> \
        --capability-map custom_components/enki/api/capability_routes_data.py
    ruff format custom_components/enki/api/capability_routes_data.py
"""

from __future__ import annotations

# capability (snake_case) -> {service slug: full route path}
CAPABILITY_ROUTES: dict[str, dict[str, str]] = {
    "N2": {
        "api-enki-mobile-bff-prod": "/api-enki-mobile-bff-prod/v1/groups/{groupId}/N2",
    },
    "_reset": {
        "api-enki-view-prod": "/api-enki-view-prod/v1/views/{id}/_reset",
    },
    "account": {
        "api-enki-alexa-mapper-prod": "/api-enki-alexa-mapper-prod/v1/account",
        "api-enki-leroy-merlin-prod": "/api-enki-leroy-merlin-prod/v1/account",
        "api-enki-netatmo-prod": "/api-enki-netatmo-prod/v1/account",
        "api-enki-philips-prod": "/api-enki-philips-prod/v1/account",
        "api-enki-sauter-prod": "/api-enki-sauter-prod/v1/account",
        "api-enki-somfy-prod": "/api-enki-somfy-prod/v1/account",
        "api-enki-tahoma-prod": "/api-enki-tahoma-prod/v1/account",
        "api-enki-wiz-prod": "/api-enki-wiz-prod/v1/account",
    },
    "accounts": {
        "api-enki-diagral-prod": "/api-enki-diagral-prod/v1/accounts",
        "api-enki-tapo-prod": "/api-enki-tapo-prod/v1/accounts",
    },
    "activate": {
        "api-enki-scenario-prod": "/api-enki-scenario-prod/v1/scenarios/{scenarioId}/activate",
    },
    "activate_contact_detection": {
        "api-enki-contact-sensor-prod": "/api-enki-contact-sensor-prod/v1/sensors/{nodeId}/activate-contact-detection",
    },
    "activate_vibration_detection": {
        "api-enki-contact-sensor-prod": "/api-enki-contact-sensor-prod/v1/sensors/{nodeId}/activate-vibration-detection",
    },
    "add_node": {
        "api-enki-room-prod": "/api-enki-room-prod/v1/rooms/{roomId}/add-node",
    },
    "additional_info": {
        "api-enki-home-prod": "/api-enki-home-prod/v1/homes/{homeId}/additional-info",
    },
    "advice": {
        "api-enki-coach-energy-prod": "/api-enki-coach-energy-prod/v1/advice",
    },
    "associate": {
        "api-enki-netatmo-prod": "/api-enki-netatmo-prod/v1/account/{accountId}/associate",
        "api-enki-philips-prod": "/api-enki-philips-prod/v1/account/{accountId}/associate",
        "api-enki-somfy-prod": "/api-enki-somfy-prod/v1/account/{accountId}/associate",
        "api-enki-tapo-prod": "/api-enki-tapo-prod/v1/accounts/{accountId}/associate",
    },
    "associations": {
        "api-enki-tapo-prod": "/api-enki-tapo-prod/v1/accounts/{accountId}/associations",
    },
    "boiler_module_pairing_status": {
        "api-enki-avidsen-thermostat-prod": "/api-enki-avidsen-thermostat-prod/v1/nodes/{nodeId}/boiler-module-pairing-status",
    },
    "can_pair": {
        "api-enki-avidsen-thermostat-prod": "/api-enki-avidsen-thermostat-prod/v1/equipment/can-pair",
    },
    "capability_value": {
        "api-enki-sauter-prod": "/api-enki-sauter-prod/v1/nodes/{nodeId}/capability-value",
    },
    "card": {
        "api-enki-coach-energy-prod": "/api-enki-coach-energy-prod/v1/curtailment/card",
    },
    "certificate": {
        "api-enki-payment-prod": "/api-enki-payment-prod/v1/certificate",
    },
    "change_airconditioner_state": {
        "api-enki-equation-airco-prod": "/api-enki-equation-airco-prod/v1/equation-airco/{nodeId}/change-airconditioner-state",
    },
    "change_airflow_mode": {
        "api-enki-airflow-prod": "/api-enki-airflow-prod/v1/airflow/{nodeId}/change-airflow-mode",
        "api-enki-group-prod": "/api-enki-group-prod/v1/groups/{id}/change-airflow-mode",
    },
    "change_ballast_configuration": {
        "api-enki-lighting-prod": "/api-enki-lighting-prod/v1/lighting/{nodeId}/change-ballast-configuration",
    },
    "change_boiler_trigger_permissions": {
        "api-enki-thermostat-prod": "/api-enki-thermostat-prod/v1/heating/{nodeId}/change-boiler-trigger-permissions",
    },
    "change_child_lock": {
        "api-enki-thermostat-prod": "/api-enki-thermostat-prod/v1/heating/{nodeId}/change-child-lock",
    },
    "change_detection_zone": {
        "api-enki-lexman-camera-meari-prod": "/api-enki-lexman-camera-meari-prod/v1/camera/{nodeId}/change-detection-zone",
    },
    "change_dimming_mode": {
        "api-enki-lighting-prod": "/api-enki-lighting-prod/v1/lighting/{nodeId}/change-dimming-mode",
    },
    "change_fan_rotation_direction": {
        "api-enki-airflow-prod": "/api-enki-airflow-prod/v1/airflow/{nodeId}/change-fan-rotation-direction",
    },
    "change_fan_speed": {
        "api-enki-airflow-prod": "/api-enki-airflow-prod/v1/airflow/{nodeId}/change-fan-speed",
        "api-enki-group-prod": "/api-enki-group-prod/v1/groups/{id}/change-fan-speed",
    },
    "change_flip_screen_mode": {
        "api-enki-lexman-camera-meari-prod": "/api-enki-lexman-camera-meari-prod/v1/camera/{nodeId}/change-flip-screen-mode",
    },
    "change_group_security": {
        "api-enki-siren-prod": "/api-enki-siren-prod/v1/groups/{nodeId}/change-group-security",
    },
    "change_humanoid_detection_sensitivity_level": {
        "api-enki-lexman-camera-meari-prod": "/api-enki-lexman-camera-meari-prod/v1/camera/{nodeId}/change-humanoid-detection-sensitivity-level",
    },
    "change_indicator_light_mode": {
        "api-enki-lexman-camera-meari-prod": "/api-enki-lexman-camera-meari-prod/v1/camera/{nodeId}/change-indicator-light-mode",
    },
    "change_light_mode": {
        "api-enki-lexman-camera-meari-prod": "/api-enki-lexman-camera-meari-prod/v1/camera/{nodeId}/change-light-mode",
    },
    "change_light_state": {
        "api-enki-group-prod": "/api-enki-group-prod/v1/groups/{id}/change-light-state",
        "api-enki-lighting-prod": "/api-enki-lighting-prod/v1/lighting/{nodeId}/change-light-state",
    },
    "change_max_cycles": {
        "api-enki-thermostat-prod": "/api-enki-thermostat-prod/v1/heating/{nodeId}/change-max-cycles",
    },
    "change_min_operating_time": {
        "api-enki-thermostat-prod": "/api-enki-thermostat-prod/v1/heating/{nodeId}/change-min-operating-time",
    },
    "change_motion_detection_mode": {
        "api-enki-lexman-camera-meari-prod": "/api-enki-lexman-camera-meari-prod/v1/camera/{nodeId}/change-motion-detection-mode",
    },
    "change_motion_detection_sensitivity_level": {
        "api-enki-lexman-camera-meari-prod": "/api-enki-lexman-camera-meari-prod/v1/camera/{nodeId}/change-motion-detection-sensitivity-level",
    },
    "change_night_vision_mode": {
        "api-enki-lexman-camera-meari-prod": "/api-enki-lexman-camera-meari-prod/v1/camera/{nodeId}/change-night-vision-mode",
    },
    "change_occupancy_mode": {
        "api-enki-presence-detector-prod": "/api-enki-presence-detector-prod/v1/sensors/{nodeId}/change-occupancy-mode",
    },
    "change_offset_temperature": {
        "api-enki-thermostat-prod": "/api-enki-thermostat-prod/v1/heating/{nodeId}/change-offset-temperature",
    },
    "change_portal_state": {
        "api-enki-videophone-prod": "/api-enki-videophone-prod/v1/videophone/{nodeId}/change-portal-state",
    },
    "change_power_intensity": {
        "api-enki-group-prod": "/api-enki-group-prod/v1/groups/{id}/change-power-intensity",
        "api-enki-power-prod": "/api-enki-power-prod/v1/power/{nodeId}/change-power-intensity",
    },
    "change_preheating_status": {
        "api-enki-thermostat-prod": "/api-enki-thermostat-prod/v1/heating/{nodeId}/change-preheating-status",
    },
    "change_recording_duration": {
        "api-enki-lexman-camera-meari-prod": "/api-enki-lexman-camera-meari-prod/v1/camera/{nodeId}/change-recording-duration",
    },
    "change_remote_mode": {
        "api-enki-lighting-remote-control-prod": "/api-enki-lighting-remote-control-prod/v1/lightingRemoteControl/{remoteControlNodeId}/change-remote-mode",
    },
    "change_roller_shutter_mode": {
        "api-enki-rolling-prod": "/api-enki-rolling-prod/v1/shutter/{nodeId}/change-roller-shutter-mode",
    },
    "change_sdp_candidates_info": {
        "api-enki-videophone-prod": "/api-enki-videophone-prod/v1/videophone/{nodeId}/change-sdp-candidates-info",
    },
    "change_security": {
        "api-enki-siren-prod": "/api-enki-siren-prod/v1/security/{nodeId}/change-security",
    },
    "change_shutter_calibration_mode": {
        "api-enki-rolling-prod": "/api-enki-rolling-prod/v1/shutter/{nodeId}/change-shutter-calibration-mode",
    },
    "change_shutter_position": {
        "api-enki-group-prod": "/api-enki-group-prod/v1/groups/{id}/change-shutter-position",
        "api-enki-rolling-prod": "/api-enki-rolling-prod/v1/shutter/{nodeId}/change-shutter-position",
    },
    "change_siren_status": {
        "api-enki-siren-prod": "/api-enki-siren-prod/v1/siren/{nodeId}/change-siren-status",
    },
    "change_thermostat_hysteresis": {
        "api-enki-thermostat-prod": "/api-enki-thermostat-prod/v1/heating/{nodeId}/change-thermostat-hysteresis",
    },
    "change_vibration_sensibility_level": {
        "api-enki-contact-sensor-prod": "/api-enki-contact-sensor-prod/v1/sensors/{nodeId}/change-vibration-sensibility-level",
    },
    "change_videophone_call": {
        "api-enki-videophone-prod": "/api-enki-videophone-prod/v1/videophone/{nodeId}/change-videophone-call",
    },
    "change_videophone_config": {
        "api-enki-videophone-prod": "/api-enki-videophone-prod/v1/videophone/{nodeId}/change-videophone-config",
    },
    "change_water_heater_mode": {
        "api-enki-equation-water-heater-prod": "/api-enki-equation-water-heater-prod/v1/equation-water-heater/{nodeId}/change-water-heater-mode",
    },
    "change_window_open_detection_mode": {
        "api-enki-thermostat-prod": "/api-enki-thermostat-prod/v1/heating/{nodeId}/change-window-open-detection-mode",
    },
    "check_airconditioner_error": {
        "api-enki-equation-airco-prod": "/api-enki-equation-airco-prod/v1/equation-airco/{nodeId}/check-airconditioner-error",
    },
    "check_airconditioner_state": {
        "api-enki-equation-airco-prod": "/api-enki-equation-airco-prod/v1/equation-airco/{nodeId}/check-airconditioner-state",
    },
    "check_airflow_mode": {
        "api-enki-airflow-prod": "/api-enki-airflow-prod/v1/airflow/{nodeId}/check-airflow-mode",
    },
    "check_alert": {
        "api-enki-siren-prod": "/api-enki-siren-prod/v1/alerts/{nodeId}/check-alert",
    },
    "check_ballast_configuration": {
        "api-enki-lighting-prod": "/api-enki-lighting-prod/v1/lighting/{nodeId}/check-ballast-configuration",
    },
    "check_battery_health": {
        "api-enki-battery-health-prod": "/api-enki-battery-health-prod/v1/sensors/{nodeId}/check-battery-health",
    },
    "check_boiler_trigger_permissions": {
        "api-enki-thermostat-prod": "/api-enki-thermostat-prod/v1/heating/{nodeId}/check-boiler-trigger-permissions",
    },
    "check_brightness_level": {
        "api-enki-luminosity-sensor-prod": "/api-enki-luminosity-sensor-prod/v1/sensors/{nodeId}/check-brightness-level",
    },
    "check_camera_connect_wss": {
        "api-enki-lexman-camera-meari-prod": "/api-enki-lexman-camera-meari-prod/v1/camera/{nodeId}/check-camera-connect-wss",
    },
    "check_camera_events": {
        "api-enki-lexman-camera-meari-prod": "/api-enki-lexman-camera-meari-prod/v1/camera/{nodeId}/check-camera-events",
    },
    "check_camera_status": {
        "api-enki-lexman-camera-meari-prod": "/api-enki-lexman-camera-meari-prod/v1/camera/{nodeId}/check-camera-status",
    },
    "check_channel1_electrical_power": {
        "api-enki-power-prod": "/api-enki-power-prod/v1/power/{nodeId}/check-channel1-electrical-power",
    },
    "check_channel2_electrical_power": {
        "api-enki-power-prod": "/api-enki-power-prod/v1/power/{nodeId}/check-channel2-electrical-power",
    },
    "check_child_lock": {
        "api-enki-thermostat-prod": "/api-enki-thermostat-prod/v1/heating/{nodeId}/check-child-lock",
    },
    "check_co2": {
        "api-enki-station-meteo-netatmo-prod": "/api-enki-station-meteo-netatmo-prod/v1/weather-station/{nodeId}/check-co2",
    },
    "check_contact_detection_activation": {
        "api-enki-contact-sensor-prod": "/api-enki-contact-sensor-prod/v1/sensors/{nodeId}/check-contact-detection-activation",
    },
    "check_contact_sensor_state": {
        "api-enki-contact-sensor-prod": "/api-enki-contact-sensor-prod/v1/sensors/{nodeId}/check-contact-sensor-state",
    },
    "check_current_humidity": {
        "api-enki-temperature-humidity-sensor-prod": "/api-enki-temperature-humidity-sensor-prod/v1/sensors/{nodeId}/check-current-humidity",
    },
    "check_current_temperature": {
        "api-enki-temperature-humidity-sensor-prod": "/api-enki-temperature-humidity-sensor-prod/v1/sensors/{nodeId}/check-current-temperature",
    },
    "check_detection_zone": {
        "api-enki-lexman-camera-meari-prod": "/api-enki-lexman-camera-meari-prod/v1/camera/{nodeId}/check-detection-zone",
    },
    "check_dimmer_mode": {
        "api-enki-power-prod": "/api-enki-power-prod/v1/power/{nodeId}/check-dimmer-mode",
    },
    "check_dimming_mode": {
        "api-enki-lighting-prod": "/api-enki-lighting-prod/v1/lighting/{nodeId}/check-dimming-mode",
    },
    "check_electrical_power": {
        "api-enki-power-prod": "/api-enki-power-prod/v1/power/{nodeId}/check-electrical-power",
    },
    "check_electrical_power_restart_behaviour": {
        "api-enki-power-prod": "/api-enki-power-prod/v1/power/{nodeId}/check-electrical-power-restart-behaviour",
    },
    "check_energy_mode": {
        "api-enki-consumption-prod": "/api-enki-consumption-prod/v1/energy/{nodeId}/check-energy-mode",
    },
    "check_external_load_shedding": {
        "api-enki-thermostat-prod": "/api-enki-thermostat-prod/v1/heating/{nodeId}/check-external-load-shedding",
    },
    "check_fan_rotation_direction": {
        "api-enki-airflow-prod": "/api-enki-airflow-prod/v1/airflow/{nodeId}/check-fan-rotation-direction",
    },
    "check_fan_speed": {
        "api-enki-airflow-prod": "/api-enki-airflow-prod/v1/airflow/{nodeId}/check-fan-speed",
    },
    "check_firmware_update_status": {
        "api-enki-lexman-camera-meari-prod": "/api-enki-lexman-camera-meari-prod/v1/camera/{nodeId}/check-firmware-update-status",
    },
    "check_group_security": {
        "api-enki-siren-prod": "/api-enki-siren-prod/v1/groups/{nodeId}/check-group-security",
    },
    "check_illuminance_level": {
        "api-enki-luminosity-sensor-prod": "/api-enki-luminosity-sensor-prod/v1/sensors/{nodeId}/check-illuminance-level",
    },
    "check_indoor_air_temperature_humidity_analysis": {
        "api-enki-smoke-detector-prod": "/api-enki-smoke-detector-prod/v1/sensors/{nodeId}/check-indoor-air-temperature-humidity-analysis",
    },
    "check_instant_consumption": {
        "api-enki-consumption-prod": "/api-enki-consumption-prod/v1/consumption/{nodeId}/check-instant-consumption",
    },
    "check_leader_mode": {
        "api-enki-thermostat-prod": "/api-enki-thermostat-prod/v1/heating/{nodeId}/check-leader-mode",
    },
    "check_light_state": {
        "api-enki-lighting-prod": "/api-enki-lighting-prod/v1/lighting/{nodeId}/check-light-state",
    },
    "check_max_cycles": {
        "api-enki-thermostat-prod": "/api-enki-thermostat-prod/v1/heating/{nodeId}/check-max-cycles",
    },
    "check_min_operating_time": {
        "api-enki-thermostat-prod": "/api-enki-thermostat-prod/v1/heating/{nodeId}/check-min-operating-time",
    },
    "check_motion_detection": {
        "api-enki-presence-detector-prod": "/api-enki-presence-detector-prod/v1/sensors/{nodeId}/check-motion-detection",
    },
    "check_noise": {
        "api-enki-station-meteo-netatmo-prod": "/api-enki-station-meteo-netatmo-prod/v1/weather-station/{nodeId}/check-noise",
    },
    "check_occupancy": {
        "api-enki-presence-detector-prod": "/api-enki-presence-detector-prod/v1/sensors/{nodeId}/check-occupancy",
    },
    "check_occupancy_mode": {
        "api-enki-presence-detector-prod": "/api-enki-presence-detector-prod/v1/sensors/{nodeId}/check-occupancy-mode",
    },
    "check_offset_temperature": {
        "api-enki-thermostat-prod": "/api-enki-thermostat-prod/v1/heating/{nodeId}/check-offset-temperature",
    },
    "check_pilot_wire_state": {
        "api-enki-thermostat-prod": "/api-enki-thermostat-prod/v1/heating/{nodeId}/check-pilot-wire-state",
    },
    "check_power_intensity": {
        "api-enki-power-prod": "/api-enki-power-prod/v1/power/{nodeId}/check-power-intensity",
    },
    "check_power_production": {
        "api-enki-energy-production-prod": "/api-enki-energy-production-prod/v1/energy-production/{nodeId}/check-power-production",
    },
    "check_preheating": {
        "api-enki-thermostat-prod": "/api-enki-thermostat-prod/v1/heating/{nodeId}/check-preheating",
    },
    "check_preheating_status": {
        "api-enki-thermostat-prod": "/api-enki-thermostat-prod/v1/heating/{nodeId}/check-preheating-status",
    },
    "check_presence_detection": {
        "api-enki-presence-detector-prod": "/api-enki-presence-detector-prod/v1/sensors/{nodeId}/check-presence-detection",
    },
    "check_pressure": {
        "api-enki-station-meteo-netatmo-prod": "/api-enki-station-meteo-netatmo-prod/v1/weather-station/{nodeId}/check-pressure",
    },
    "check_roller_shutter_state": {
        "api-enki-rolling-prod": "/api-enki-rolling-prod/v1/shutter/{nodeId}/check-roller-shutter-state",
    },
    "check_sdp_candidates_info": {
        "api-enki-videophone-prod": "/api-enki-videophone-prod/v1/videophone/{nodeId}/check-sdp-candidates-info",
    },
    "check_security": {
        "api-enki-siren-prod": "/api-enki-siren-prod/v1/security/{nodeId}/check-security",
    },
    "check_shutter_opening": {
        "api-enki-rolling-prod": "/api-enki-rolling-prod/v1/shutter/{nodeId}/check-shutter-opening",
    },
    "check_shutter_position": {
        "api-enki-rolling-prod": "/api-enki-rolling-prod/v1/shutter/{nodeId}/check-shutter-position",
    },
    "check_siren_global_state": {
        "api-enki-siren-prod": "/api-enki-siren-prod/v1/siren/{nodeId}/check-siren-global-state",
    },
    "check_siren_state": {
        "api-enki-siren-prod": "/api-enki-siren-prod/v1/siren/{nodeId}/check-siren-state",
    },
    "check_smoke_alarm_status": {
        "api-enki-smoke-detector-prod": "/api-enki-smoke-detector-prod/v1/sensors/{nodeId}/check-smoke-alarm-status",
    },
    "check_thermostat_hysteresis": {
        "api-enki-thermostat-prod": "/api-enki-thermostat-prod/v1/heating/{nodeId}/check-thermostat-hysteresis",
    },
    "check_thermostat_running_state": {
        "api-enki-thermostat-prod": "/api-enki-thermostat-prod/v1/heating/{nodeId}/check-thermostat-running-state",
    },
    "check_thermostat_target_temperature": {
        "api-enki-thermostat-prod": "/api-enki-thermostat-prod/v1/heating/{nodeId}/check-thermostat-target-temperature",
    },
    "check_turn_info": {
        "api-enki-videophone-prod": "/api-enki-videophone-prod/v1/videophone/{nodeId}/check-turn-info",
    },
    "check_vibration_detection": {
        "api-enki-contact-sensor-prod": "/api-enki-contact-sensor-prod/v1/sensors/{nodeId}/check-vibration-detection",
    },
    "check_vibration_detection_activation": {
        "api-enki-contact-sensor-prod": "/api-enki-contact-sensor-prod/v1/sensors/{nodeId}/check-vibration-detection-activation",
    },
    "check_vibration_sensibility_level": {
        "api-enki-contact-sensor-prod": "/api-enki-contact-sensor-prod/v1/sensors/{nodeId}/check-vibration-sensibility-level",
    },
    "check_videophone_events": {
        "api-enki-videophone-prod": "/api-enki-videophone-prod/v1/videophone/{nodeId}/check-videophone-events",
    },
    "check_videophone_state": {
        "api-enki-videophone-prod": "/api-enki-videophone-prod/v1/videophone/{nodeId}/check-videophone-state",
    },
    "check_water_heater_error": {
        "api-enki-equation-water-heater-prod": "/api-enki-equation-water-heater-prod/v1/equation-water-heater/{nodeId}/check-water-heater-error",
    },
    "check_water_heater_mode": {
        "api-enki-equation-water-heater-prod": "/api-enki-equation-water-heater-prod/v1/equation-water-heater/{nodeId}/check-water-heater-mode",
    },
    "check_water_sensor_state": {
        "api-enki-water-leak-detector-prod": "/api-enki-water-leak-detector-prod/v1/detectors/{nodeId}/check-water-sensor-state",
    },
    "check_window_open_detection": {
        "api-enki-thermostat-prod": "/api-enki-thermostat-prod/v1/heating/{nodeId}/check-window-open-detection",
    },
    "check_window_open_detection_mode": {
        "api-enki-thermostat-prod": "/api-enki-thermostat-prod/v1/heating/{nodeId}/check-window-open-detection-mode",
    },
    "close": {
        "api-enki-user-information-prod": "/api-enki-user-information-prod/v1/user-informations/{informationId}/close",
    },
    "command_override_infos": {
        "api-enki-mobile-heating-bff-prod": "/api-enki-mobile-heating-bff-prod/v1/heating/command-override-infos",
    },
    "configuration": {
        "api-enki-alexa-mapper-prod": "/api-enki-alexa-mapper-prod/v1/configuration",
        "api-enki-diagral-prod": "/api-enki-diagral-prod/v1/configuration",
        "api-enki-leroy-merlin-prod": "/api-enki-leroy-merlin-prod/v1/configuration",
        "api-enki-netatmo-prod": "/api-enki-netatmo-prod/v1/configuration",
        "api-enki-philips-prod": "/api-enki-philips-prod/v1/configuration",
        "api-enki-sauter-prod": "/api-enki-sauter-prod/v1/configuration",
        "api-enki-tahoma-prod": "/api-enki-tahoma-prod/v1/configuration",
        "api-enki-tapo-prod": "/api-enki-tapo-prod/v1/configuration",
        "api-enki-wiz-prod": "/api-enki-wiz-prod/v1/configuration",
    },
    "consents": {
        "api-enki-consent-prod": "/api-enki-consent-prod/v1/consents",
        "api-enki-mobile-bff-prod": "/api-enki-mobile-bff-prod/v1/consents",
    },
    "consumption": {
        "api-enki-coach-energy-prod": "/api-enki-coach-energy-prod/v1/coach-energy/extended/consumption",
    },
    "countries": {
        "api-enki-country-prod": "/api-enki-country-prod/v1/countries",
    },
    "current": {
        "api-enki-energy-subscription-prod": "/api-enki-energy-subscription-prod/v1/energy-subscriptions/current",
        "api-enki-heating-controller-prod": "/api-enki-heating-controller-prod/v1/nodes/{nodeId}/policies/current",
        "api-enki-user-prod": "/api-enki-user-prod/v1/users/current",
    },
    "currentMode": {
        "api-enki-home-security-prod": "/api-enki-home-security-prod/v1/security/{securityId}/homes/{homeId}/currentMode",
    },
    "current_price": {
        "api-enki-energy-production-prod": "/api-enki-energy-production-prod/v1/energy-production/current-price",
    },
    "dashboard": {
        "api-enki-mobile-bff-prod": "/api-enki-mobile-bff-prod/v1/scenario/dashboard",
    },
    "default": {
        "api-enki-mobile-bff-prod": "/api-enki-mobile-bff-prod/v1/views/default",
    },
    "default_schedule": {
        "api-enki-schedule-prod": "/api-enki-schedule-prod/v1/devices/{deviceId}/default-schedule",
    },
    "delay": {
        "api-enki-home-security-prod": "/api-enki-home-security-prod/v1/security/{securityId}/homes/{homeId}/delay",
    },
    "delete_camera_events": {
        "api-enki-lexman-camera-meari-prod": "/api-enki-lexman-camera-meari-prod/v1/camera/{nodeId}/delete-camera-events",
    },
    "device_types": {
        "api-enki-referentiel-agg-prod": "/api-enki-referentiel-agg-prod/v1/device-types",
    },
    "devices": {
        "api-enki-referentiel-agg-prod": "/api-enki-referentiel-agg-prod/v1/devices",
    },
    "disable": {
        "api-enki-heating-prod": "/api-enki-heating-prod/v1/schedules/{scheduleId}/disable",
        "api-enki-schedule-prod": "/api-enki-schedule-prod/v1/schedules/{scheduleId}/disable",
    },
    "dongle": {
        "api-enki-rts-prod": "/api-enki-rts-prod/v1/dongle",
    },
    "eligibility": {
        "api-enki-coach-energy-prod": "/api-enki-coach-energy-prod/v1/flexibility/eligibility",
    },
    "eligible_device_card": {
        "api-enki-coach-energy-prod": "/api-enki-coach-energy-prod/v1/flexibility/eligible-device-card",
    },
    "enable": {
        "api-enki-heating-prod": "/api-enki-heating-prod/v1/schedules/{scheduleId}/enable",
        "api-enki-scenario-prod": "/api-enki-scenario-prod/v1/scenarios/{scenarioId}/enable",
        "api-enki-schedule-prod": "/api-enki-schedule-prod/v1/schedules/{scheduleId}/enable",
    },
    "endpoints": {
        "api-enki-mobile-bff-prod": "/api-enki-mobile-bff-prod/v1/remote/{nodeId}/endpoints",
    },
    "enedis_consents": {
        "api-enki-consent-prod": "/api-enki-consent-prod/v1/enedis-consents",
        "api-enki-mobile-bff-prod": "/api-enki-mobile-bff-prod/v1/enedis-consents",
    },
    "energy_subscriptions": {
        "api-enki-energy-subscription-prod": "/api-enki-energy-subscription-prod/v1/energy-subscriptions",
    },
    "esdk_v2": {
        "api-enki-esdk-prod": "/api-enki-esdk-prod/v1/provisioning/esdk-v2",
    },
    "events": {
        "api-enki-lexman-camera-prod": "/api-enki-lexman-camera-prod/v1/events",
    },
    "expired": {
        "api-enki-mobile-bff-prod": "/api-enki-mobile-bff-prod/v1/partner/expired",
    },
    "finish_provisioning": {
        "api-enki-lexman-camera-meari-prod": "/api-enki-lexman-camera-meari-prod/v1/{nodeId}/finish-provisioning",
    },
    "finish_reonboarding": {
        "api-enki-lexman-camera-meari-prod": "/api-enki-lexman-camera-meari-prod/v1/{nodeId}/finish-reonboarding",
    },
    "firmware": {
        "api-enki-lexman-chargepoint-prod": "/api-enki-lexman-chargepoint-prod/v1/chargepoints/{nodeId}/firmware",
    },
    "flexibility": {
        "api-enki-coach-energy-prod": "/api-enki-coach-energy-prod/v1/flexibility",
    },
    "format_sd_card": {
        "api-enki-lexman-camera-meari-prod": "/api-enki-lexman-camera-meari-prod/v1/camera/{nodeId}/format-sd-card",
    },
    "freeaccessmode": {
        "api-enki-lexman-chargepoint-prod": "/api-enki-lexman-chargepoint-prod/v1/chargepoints/{nodeId}/freeaccessmode",
    },
    "get_associations": {
        "api-enki-alexa-mapper-prod": "/api-enki-alexa-mapper-prod/v1/account/{accountId}/get-associations",
        "api-enki-netatmo-prod": "/api-enki-netatmo-prod/v1/account/{accountId}/get-associations",
        "api-enki-philips-prod": "/api-enki-philips-prod/v1/account/{accountId}/get-associations",
        "api-enki-somfy-prod": "/api-enki-somfy-prod/v1/account/{accountId}/get-associations",
    },
    "group": {
        "api-enki-room-prod": "/api-enki-room-prod/v1/room-types/group",
    },
    "groupTypes": {
        "api-enki-group-prod": "/api-enki-group-prod/v1/groupTypes",
        "api-enki-mobile-bff-prod": "/api-enki-mobile-bff-prod/v1/groupTypes",
    },
    "groups": {
        "api-enki-group-prod": "/api-enki-group-prod/v1/groups",
    },
    "health": {
        "api-enki-coach-energy-prod": "/api-enki-coach-energy-prod/v1/coach-energy/health",
    },
    "homes": {
        "api-enki-home-prod": "/api-enki-home-prod/v1/homes",
    },
    "import": {
        "api-enki-diagral-prod": "/api-enki-diagral-prod/v1/accounts/{accountId}/import",
        "api-enki-sauter-prod": "/api-enki-sauter-prod/v1/account/{accountId}/import",
        "api-enki-tahoma-prod": "/api-enki-tahoma-prod/v1/account/{accountId}/import",
        "api-enki-wiz-prod": "/api-enki-wiz-prod/v1/account/{accountId}/import",
    },
    "is_eligible": {
        "api-enki-schedule-prod": "/api-enki-schedule-prod/v1/devices/{deviceId}/is-eligible",
    },
    "label": {
        "api-enki-schedule-prod": "/api-enki-schedule-prod/v1/schedules/{scheduleId}/label",
    },
    "link_node": {
        "api-enki-boiler-system-prod": "/api-enki-boiler-system-prod/v1/modules/{moduleId}/link-node",
    },
    "locale": {
        "api-enki-user-prod": "/api-enki-user-prod/v1/users/{userId}/locale",
    },
    "login": {
        "api-enki-diagral-prod": "/api-enki-diagral-prod/v1/login",
        "api-enki-leroy-merlin-prod": "/api-enki-leroy-merlin-prod/v1/login",
        "api-enki-netatmo-prod": "/api-enki-netatmo-prod/v1/login",
        "api-enki-philips-prod": "/api-enki-philips-prod/v1/login",
        "api-enki-sauter-prod": "/api-enki-sauter-prod/v1/login",
        "api-enki-somfy-prod": "/api-enki-somfy-prod/v1/login",
        "api-enki-tahoma-prod": "/api-enki-tahoma-prod/v1/login",
        "api-enki-tapo-prod": "/api-enki-tapo-prod/v1/login",
        "api-enki-wiz-prod": "/api-enki-wiz-prod/v1/login",
    },
    "manufacturers": {
        "api-enki-referentiel-agg-prod": "/api-enki-referentiel-agg-prod/v1/manufacturers",
    },
    "min_time": {
        "api-enki-boiler-system-prod": "/api-enki-boiler-system-prod/v1/modules/{moduleId}/min-time",
    },
    "modes": {
        "api-enki-heating-prod": "/api-enki-heating-prod/v1/modes",
        "api-enki-home-security-prod": "/api-enki-home-security-prod/v1/modes",
        "api-enki-mobile-bff-prod": "/api-enki-mobile-bff-prod/v1/remote/{nodeId}/modes",
    },
    "modules": {
        "api-enki-boiler-system-prod": "/api-enki-boiler-system-prod/v1/gateways/{gatewayId}/modules",
    },
    "nodes": {
        "api-enki-boiler-system-prod": "/api-enki-boiler-system-prod/v1/modules/{moduleId}/nodes",
        "api-enki-coach-energy-prod": "/api-enki-coach-energy-prod/v1/flexibility/nodes",
        "api-enki-node-agg-prod": "/api-enki-node-agg-prod/v1/nodes",
        "api-enki-user-data-agg-prod": "/api-enki-user-data-agg-prod/v1/nodes",
    },
    "notifications": {
        "api-enki-home-security-prod": "/api-enki-home-security-prod/v1/security/{securityId}/homes/{homeId}/notifications",
    },
    "offers": {
        "api-enki-coach-energy-prod": "/api-enki-coach-energy-prod/v1/advice/offers",
    },
    "oldest_home": {
        "api-enki-home-prod": "/api-enki-home-prod/v1/homes/oldest-home",
    },
    "override_commands": {
        "api-enki-command-override-prod": "/api-enki-command-override-prod/v1/override-commands",
    },
    "overview": {
        "api-enki-coach-energy-prod": "/api-enki-coach-energy-prod/v1/coach-energy/overview",
    },
    "pair": {
        "api-enki-avidsen-thermostat-prod": "/api-enki-avidsen-thermostat-prod/v1/equipment/pair",
        "api-enki-bluetooth-prod": "/api-enki-bluetooth-prod/v1/pair",
        "api-enki-dio-prod": "/api-enki-dio-prod/v1/pair",
        "api-enki-enocean-prod": "/api-enki-enocean-prod/v1/pair",
        "api-enki-lexman-camera-meari-prod": "/api-enki-lexman-camera-meari-prod/v1/pair",
        "api-enki-lexman-camera-prod": "/api-enki-lexman-camera-prod/v1/pair",
        "api-enki-lexman-chargepoint-prod": "/api-enki-lexman-chargepoint-prod/v1/pair",
        "api-enki-lexman-envertech-prod": "/api-enki-lexman-envertech-prod/v1/pair",
        "api-enki-rts-prod": "/api-enki-rts-prod/v1/pair",
        "api-enki-videophone-prod": "/api-enki-videophone-prod/v1/pair",
        "api-enki-zigbee-prod": "/api-enki-zigbee-prod/v1/pair",
    },
    "partners": {
        "api-enki-referentiel-agg-prod": "/api-enki-referentiel-agg-prod/v1/partners",
    },
    "planning": {
        "api-enki-mobile-heating-bff-prod": "/api-enki-mobile-heating-bff-prod/v1/heating/overview/planning",
    },
    "policies": {
        "api-enki-heating-controller-prod": "/api-enki-heating-controller-prod/v1/nodes/{nodeId}/policies",
    },
    "power_on_with_timer": {
        "api-enki-power-prod": "/api-enki-power-prod/v1/power/{nodeId}/power-on-with-timer",
    },
    "programmers": {
        "api-enki-programmer-prod": "/api-enki-programmer-prod/v1/programmers",
    },
    "providers": {
        "api-enki-energy-subscription-prod": "/api-enki-energy-subscription-prod/v1/providers",
    },
    "provisioning": {
        "api-enki-esdk-prod": "/api-enki-esdk-prod/v1/provisioning",
        "api-enki-gw-connect-prod": "/api-enki-gw-connect-prod/v1/provisioning",
        "api-enki-gw-essentielb-prod": "/api-enki-gw-essentielb-prod/v1/provisioning",
        "api-enki-gw-v1-prod": "/api-enki-gw-v1-prod/v1/provisioning",
    },
    "record": {
        "api-enki-videophone-prod": "/api-enki-videophone-prod/v1/videophone/{nodeId}/record",
    },
    "register": {
        "api-enki-payment-prod": "/api-enki-payment-prod/v1/iban/register",
        "api-enki-user-prod": "/api-enki-user-prod/v1/users/register",
    },
    "register_provider": {
        "api-enki-user-prod": "/api-enki-user-prod/v1/users/register-provider",
    },
    "registration": {
        "api-enki-user-information-prod": "/api-enki-user-information-prod/v1/water-heater-migration/registration",
    },
    "registrations": {
        "api-enki-survoltage-prod": "/api-enki-survoltage-prod/v1/flexibility/registrations",
    },
    "regulation_mode": {
        "api-enki-avidsen-thermostat-prod": "/api-enki-avidsen-thermostat-prod/v1/thermostat/{nodeId}/regulation-mode",
    },
    "reset_password": {
        "api-enki-user-prod": "/api-enki-user-prod/v1/users/email/{mail}/reset-password",
    },
    "rooms": {
        "api-enki-mobile-heating-bff-prod": "/api-enki-mobile-heating-bff-prod/v1/heating/overview/rooms",
        "api-enki-room-prod": "/api-enki-room-prod/v1/rooms",
    },
    "save": {
        "api-enki-schedule-prod": "/api-enki-schedule-prod/v1/schedules/peak-off-peak/save",
    },
    "scenario": {
        "api-enki-mobile-bff-prod": "/api-enki-mobile-bff-prod/v1/remote/{nodeId}/scenario",
    },
    "scenarios": {
        "api-enki-scenario-prod": "/api-enki-scenario-prod/v1/scenarios",
    },
    "schedules": {
        "api-enki-heating-prod": "/api-enki-heating-prod/v1/schedules",
        "api-enki-schedule-prod": "/api-enki-schedule-prod/v1/schedules",
    },
    "sections": {
        "api-enki-view-prod": "/api-enki-view-prod/v1/views/{id}/sections",
    },
    "security": {
        "api-enki-home-security-prod": "/api-enki-home-security-prod/v1/security",
        "api-enki-mobile-bff-prod": "/api-enki-mobile-bff-prod/v1/scenario/security",
    },
    "settings": {
        "api-enki-mobile-config-prod": "/api-enki-mobile-config-prod/v1/settings",
    },
    "smartcharge": {
        "api-enki-lexman-chargepoint-prod": "/api-enki-lexman-chargepoint-prod/v1/chargepoints/{nodeId}/smartcharge",
    },
    "specific": {
        "api-enki-energy-production-prod": "/api-enki-energy-production-prod/v1/energy-production/{nodeId}/specific",
    },
    "specific_granularity": {
        "api-enki-temperature-humidity-sensor-prod": "/api-enki-temperature-humidity-sensor-prod/v1/sensors/bff/nodes/{nodeId}/specific-granularity",
    },
    "start": {
        "api-enki-heating-prod": "/api-enki-heating-prod/v1/modes/{modeId}/start",
    },
    "start_reonboarding": {
        "api-enki-lexman-camera-meari-prod": "/api-enki-lexman-camera-meari-prod/v1/{nodeId}/start-reonboarding",
    },
    "status": {
        "api-enki-coach-energy-prod": "/api-enki-coach-energy-prod/v1/advice/{adviceId}/status",
    },
    "stop": {
        "api-enki-heating-prod": "/api-enki-heating-prod/v1/modes/{modeId}/stop",
        "api-enki-scenario-prod": "/api-enki-scenario-prod/v1/scenarios/{scenarioId}/stop",
    },
    "stop_change_shutter_position": {
        "api-enki-rolling-prod": "/api-enki-rolling-prod/v1/shutter/{nodeId}/stop-change-shutter-position",
    },
    "subscription": {
        "api-enki-survoltage-prod": "/api-enki-survoltage-prod/v1/curtailment/subscription",
    },
    "switch_channel1_electrical_power": {
        "api-enki-power-prod": "/api-enki-power-prod/v1/power/{nodeId}/switch-channel1-electrical-power",
    },
    "switch_channel2_electrical_power": {
        "api-enki-power-prod": "/api-enki-power-prod/v1/power/{nodeId}/switch-channel2-electrical-power",
    },
    "switch_dimmer_mode": {
        "api-enki-power-prod": "/api-enki-power-prod/v1/power/{nodeId}/switch-dimmer-mode",
    },
    "switch_electrical_power": {
        "api-enki-group-prod": "/api-enki-group-prod/v1/groups/{id}/switch-electrical-power",
        "api-enki-power-prod": "/api-enki-power-prod/v1/power/{nodeId}/switch-electrical-power",
    },
    "switch_electrical_power_restart_behaviour": {
        "api-enki-power-prod": "/api-enki-power-prod/v1/power/{nodeId}/switch-electrical-power-restart-behaviour",
    },
    "switch_energy_mode": {
        "api-enki-consumption-prod": "/api-enki-consumption-prod/v1/energy/{nodeId}/switch-energy-mode",
    },
    "switch_instant_power_report": {
        "api-enki-consumption-prod": "/api-enki-consumption-prod/v1/energy/{nodeId}/switch-instant-power-report",
    },
    "switch_pilot_wire_mode": {
        "api-enki-thermostat-prod": "/api-enki-thermostat-prod/v1/heating/{nodeId}/switch-pilot-wire-mode",
    },
    "switch_roller_shutter": {
        "api-enki-group-prod": "/api-enki-group-prod/v1/groups/{id}/switch-roller-shutter",
        "api-enki-rolling-prod": "/api-enki-rolling-prod/v1/shutter/{nodeId}/switch-roller-shutter",
    },
    "switch_siren_status": {
        "api-enki-siren-prod": "/api-enki-siren-prod/v1/siren/{nodeId}/switch-siren-status",
    },
    "themes": {
        "api-enki-product-highlight-prod": "/api-enki-product-highlight-prod/v1/themes",
    },
    "timers": {
        "api-enki-programmer-prod": "/api-enki-programmer-prod/v1/timers",
    },
    "timeslots": {
        "api-enki-heating-prod": "/api-enki-heating-prod/v1/schedules/{scheduleId}/timeslots",
        "api-enki-schedule-prod": "/api-enki-schedule-prod/v1/timeslots",
    },
    "transaction": {
        "api-enki-lexman-chargepoint-prod": "/api-enki-lexman-chargepoint-prod/v1/chargepoints/{nodeId}/transaction",
    },
    "unlink_node": {
        "api-enki-boiler-system-prod": "/api-enki-boiler-system-prod/v1/modules/{moduleId}/unlink-node",
    },
    "update_firmware_version": {
        "api-enki-lexman-camera-meari-prod": "/api-enki-lexman-camera-meari-prod/v1/camera/{nodeId}/update-firmware-version",
    },
    "update_heating_state": {
        "api-enki-heating-controller-prod": "/api-enki-heating-controller-prod/v1/nodes/{nodeId}/update-heating-state",
    },
    "user_informations": {
        "api-enki-user-information-prod": "/api-enki-user-information-prod/v1/user-informations",
    },
    "version": {
        "api-enki-avidsen-thermostat-prod": "/api-enki-avidsen-thermostat-prod/v1/nodes/{nodeId}/version",
    },
    "versions": {
        "api-enki-coach-energy-prod": "/api-enki-coach-energy-prod/v1/advice/offers/versions",
    },
    "wake_up": {
        "api-enki-lexman-camera-meari-prod": "/api-enki-lexman-camera-meari-prod/v1/camera/{nodeId}/wake-up",
    },
    "wallet": {
        "api-enki-coach-energy-prod": "/api-enki-coach-energy-prod/v1/flexibility/wallet",
    },
    "wifi_strength": {
        "api-enki-avidsen-thermostat-prod": "/api-enki-avidsen-thermostat-prod/v1/thermostat/{nodeId}/wifi-strength",
    },
}
